language: clojure
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.lein
  - $HOME/.m2
script:
- lein cljfmt check
- lein eastwood
- lein test
after_success:
- CLOVERAGE_VERSION=1.0.7-SNAPSHOT lein with-profile test cloverage --codecov
- bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
notifications:
  email: false
  slack:
    secure: PmCAZ4U+BJVTRR6gfqgIopsDEBtSVFGxlWTmCpF0mOpFSpVTVIANrHlcZvUaMZEW5a6t16ywmDYLGJcrvV/5u7kWr/ULfCW8WSdvPufSA6NveQW+CR1FRq+XMRQaXV6mKH+Goi/D4u4cgIWyOqivJyQ/xuYtRECm+QuUJy9mh5hjcHhWJe7GWzxP9hemWmxNoaSmNlrCFZqIEtIpfdbCdR456fv2hOX9hFUoCE2sSw1bjjIIPnnm4a2foQ7A/A9EA4BX2ez/Mj+73mcMW1qfsKDjwAtmJ0PYAGhKPRe3WKvn5uqhjvbYxtGv0i8GfvYH08fJ/NhwxiLyQiiY3t9kNBt+K0Gts+y5nN9OrgRJQBYZAgxdv3hWcMoA5oBTh5oSH8Vk/e4WvHwAjbKQGcws6DUGv6YBzoYMPIO0o/MImTIUIRB2UXAmoT9fysdps7pmb7oVrpmEq5RWMbqqAyykG3ZrjDPjGYVjQBxIwQ4lIAGv5/13RSqGjQhFcKIEp6NBuhUfFhM0BxGh8lE6TtB5PskGJA/b8gPusQO8G4awopg0DXre/6DktMIJkA3OnEGrLRIjc18ooeV3jtC7EcwoaeAktwUlMU5XSaGjaOTvN0BPh84A8m9pe/tteBM2/hJOL2IXnjUzEPXIfOYfG5U5A5TfsUrzuKculKZVO0mY3IA=
