language: clojure
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.lein
  - $HOME/.m2
script:
- lein cljfmt check
- lein eastwood
- lein test
after_success:
- CLOVERAGE_VERSION=1.0.7-SNAPSHOT lein with-profile test cloverage --codecov
- bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
notifications:
  email: false
  slack:
    secure: zVHebkBNDJi6+JjxLLYbvZ+AdGYdhMjzah6ZvNMwwAslXXqQSA8MnPIEWQ2Yd4K1mpavsis6yzEcYlM9IzBUqTPgbk6gGc0PKndM8ESR1OS1JIruE+kSwoR5jnkf2DcdDiHkBVk50cAtsVyBpGla2wu7VPjtiw+Y7qFSuyrSjO6qdql0qLE4d7V0V/0pc5MyQtyeGJADcd6mEkIK9/oJhgV43ocnl7tsd78RFhhc2e5mIEy0CKkXT5lw7e0ybvpiVIws0AnzFEEoKmlEDC9wmWgygJ4DTbm/QWdmsb5i9KZdg1gGg4QIPMm68XHnV+MkzYuyefn5e0h8ri4xGR/VE6HrLa8OedgThggKWkr8vSxk1M4pM1f+BNVG5tP4eieR1MUgZW/Avax9E9RybiQqju7NyWtwF17o/WwbsonDkzMauG6Gt0Buu0MLO8mropMcUnB+/e0K0sz951Ee+qA18P1yB5+aO9WU21ycnr8v4GFLn7l+zhAAde37dFMpIb9hbiGG6iPuoKv36K2IMpwtFjYfuEg2s8iMruiFhSb9FrHJ4WXP3aC+MKONDas8DnqQgCHM9ivfCZj3ZtXDkl/CAzhTcgGBU/p5eG+yFLsiRbky+6fEW31ki3hh56MffqC/tJCkz+JMunvivK/6pjTUlcHqSDjPocz1fMaDPGdN6Sc=
